clients:
  kakao:
    uri: "https://dapi.kakao.com/v2/search/blog"
    api-key: "KakaoAK a1b39fd51e5f5d7521cd2f7286d31423"
  naver:
    uri: "https://openapi.naver.com/v1/search/blog.json"
    client-id: "oyiPzcIUZxdNSjSds6G_"
    client-secret: "8GejLtS4Ht"