openapi: 3.0.0
info:
  title: 블로그 API 명세서
  version: 1.0.0
  description: 블로그 조회 및 인기 키워드 목록 조회 서비스
servers:
  - url: http://localhost:8080
tags:
  - name: blog
paths:
  /blogs:
    get:
      tags:
        - blog
      summary: 블로그 검색
      operationId: getBlogs
      parameters:
        - in: query
          name: query
          description: 검색어
          required: true
          schema:
            type: string
        - in: query
          name: sort
          description: 정렬 유형
          schema:
            type: string 
            enum: ["ACCURACY", "RECENCY"]
        - in: query
          name: page
          description: 페이지 번호 (1-50)
          schema:
            type: integer
            minimum: 1
            maximum: 50
        - in: query
          name: size
          description: 페이지당 표출 문서 수 (1-50)
          schema:
            type: integer
            minimum: 1
            maximum: 50
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
  /blogs/top-keywords:
    get:
      tags:
        - blog
      summary: 인기 키워드 목록 조회 (Top 10, 내림차순)
      operationId: getPopularKeywords
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TopKeywordsResponse'
components:
  schemas:
    SearchResult:
      type: object
      properties:
        totalCount:
          type: integer
          description: 총 항목 개수
        totalPage:
          type: integer
          description: 총 페이지 수
        currentPage:
          type: integer
          description: 현재 페이지 번호
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
          description: 검색 결과 항목 리스트
    Document:
      type: object
      properties:
        title:
          type: string
          description: 제목
        contents:
          type: string
          description: 내용
        url:
          type: string
          description: URL
        blogName:
          type: string
          description: 블로그명
        thumbnail:
          type: string
          description: 썸네일
        dateTime:
          type: string
          description: 작성일시
    TopKeywordsResponse:
      type: object
      properties:
        keyword:
          type: string
          description: 키워드
        count:
          type: integer
          description: 검색 카운트
